### ISSUE TITLE
awesome

### ISSUE THREAD

**Issue by JacksonWang6** [Ricardokevins/fundamental-programming-ex#19]
尊敬的南大同学你好，我是华科的同学，非常感谢您开源这么优秀的代码，贵校的课程质量真的高，我想请问一下能否上传一下实验的指导书？我想学习一下，十分感谢（emmm，时间有点久远，不在也没关系的哈^_^

**Comment by Ricardokevins** [comment]
可以的，我还有保存。你这issue啥时候发的，我之前没注意到，不好意思。
我的这个课程是每一个项目对应的会有一个课件，我尽快上传到对应的文件夹里

**Comment by Ricardokevins** [comment]
> 尊敬的南大同学你好，我是华科的同学，非常感谢您开源这么优秀的代码，贵校的课程质量真的高，我想请问一下能否上传一下实验的指导书？我想学习一下，十分感谢（emmm，时间有点久远，不在也没关系的哈^_^

你好，所有的课程设计对应的ppt都已经更新到了对应的目录里
这个实验课程的设计就是第一周课做初步的基于课件的讲解实验，之后的两周做设计和代码实现，所以没有书本和教材，所需的知识也是大一上的程设基础学习的内容，这门课不做大的知识讲解，只有局部的小知识的补充

**Comment by JacksonWang6** [comment]
感谢您的分享以及耐心回复！
